# Generated by Django 3.1.2 on 2020-11-13 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_published',
            new_name='is_public',
        ),
    ]
